### ISSUE TITLE
'RobertaForSequenceClassification' object has no attribute 'embeddings'

### ISSUE THREAD

**Issue by Echoleung** [alexa/wqa-contextual-qa#2]
when i run the scrip_eval.py with the the fine-tune model generated by the script_training.sh, it has this error:
```
Traceback (most recent call last):
  File "/Volumes/Files/Documents/PycharmProjects/wqa-contextual-qa/examples/run_eval.py", line 36, in <module>
    model = model_class(args.model)
  File "/Volumes/Files/Documents/PycharmProjects/wqa-contextual-qa/examples/../coala/models.py", line 80, in __init__
    super().__init__(pretrained_huggingface_model_name_or_path)
  File "/Volumes/Files/Documents/PycharmProjects/wqa-contextual-qa/examples/../coala/models.py", line 43, in __init__
    as2encoder.embeddings = checkpoint.embeddings
  File "/usr/local/Caskroom/miniconda/base/envs/wqa-contextual-qa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RobertaForSequenceClassification' object has no attribute 'embeddings'
```
then i debug and find the checkpoint dont have the attribute 'embeddings', I want yo know why, thx.

**Comment by IvanoLauriola** [comment]
Hi, thanks for your report!
We will fix this in the next release (that will be published in a few days).
In the meanwhile, you can use a simple workaround:

Replace this line
`model = model_class(args.model) `
with this
`model = torch.load(args.model)`
in `run_eval.py:37`
